### SignUp Customer
POST localhost:8080/customer/signup
Content-Type: application/json

{
  "email": "test@naver.com",
  "name": "KANG",
  "password": "test1234",
  "phoneNumber": "010-1234-1234"
}

### SignUp Manager
POST localhost:8080/manager/signup
Content-Type: application/json

{
  "email": "test@naver.com",
  "name": "KANG",
  "password": "test1234",
  "phoneNumber": "010-1234-1234"
}

### Create Restaurant
POST localhost:8080/manager/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX01BTkFHRVIiXSwic3ViIjoidGVzdEBuYXZlci5jb20iLCJpYXQiOjE3MTQxNjA3OTksImV4cCI6MTcxNDE2NDM5OX0.Vf_GzaCp7pq0wv4H_pYlR6i5jUN9qhb1dFCWxQ-y-6v-BMoaDMx7AGoWaimceHvLz69miKQ99j_OwStoi1b_mA

{
  "name": "치킨집",
  "businessNumber": "000-00-00000-5",
  "location": "인천시",
  "capacity": 10,
  "description": "인천 BBQ 치킨집",
  "phoneNumber": "010-0000-0000"
}

### SignIn Customer
POST localhost:8080/customer/signin
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "test1234"
}

### SignIn Manager
POST localhost:8080/manager/signin
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "test1234"
}

### Reservation Customer
POST localhost:8080/customer/reservation/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sInN1YiI6InRlc3RAbmF2ZXIuY29tIiwiaWF0IjoxNzE0MDQ3NTk3LCJleHAiOjE3MTQwNTExOTd9.s07sFCsaQ9b6JvcUWbqA_V72LbK5a1G4OiwVb0pOtZHCDZ_vniXWHSXJQZaAwsOyCpNSfXn2QRg1_jr3e0FwjQ

{
  "headCount": 20,
  "reservedAt": "2024-10-31T14:30:00"
}

### Review Customer
POST localhost:8080/customer/rate/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0NVU1RPTUVSIl0sInN1YiI6InRlc3RAbmF2ZXIuY29tIiwiaWF0IjoxNzEzNjI2NDgxLCJleHAiOjE3MTM2MzAwODF9.h6N_Y8zhhaIf9ylci6-6YXxvUYhxs7B3djQWfHWDxiHILmG1Ljydxy3dTooR7JAhqkhwUH7tKOG9z4zntl3twg

{
  "rate": 4,
  "description": "괜찮습니다."
}

### Get Restaurants
GET localhost:8080/customer/restaurants
Accept: application/json

### Get Reservations
GET localhost:8080/manager/reservation/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX01BTkFHRVIiXSwic3ViIjoidGVzdEBuYXZlci5jb20iLCJpYXQiOjE3MTQwNDc1NzEsImV4cCI6MTcxNDA1MTE3MX0.S8zMsqwYuRXY1Lq8G0AiNtS7v-ovdt38dKJlGEADdVBAt-XLyHbioY8nI6Vt7r-VTG-V4AIfGkwOtZuQpsVC2g
Accept: application/json

### Decide Reservation
PUT localhost:8080/manager/reservation?restaurantid=1&reservationid=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX01BTkFHRVIiXSwic3ViIjoidGVzdEBuYXZlci5jb20iLCJpYXQiOjE3MTQxNjcyNzksImV4cCI6MTcxNDE3MDg3OX0.lt_zG2OqKvVM31LL5Om5Jpcnv6JQd7dTLg4Jr9diGvgNisuxbLZ3YNMfaars5hDR5-C1LBpMkWCvfbb8YQ-k_Q

{
  "status": "ACCEPTED"
}

###