spring:
  application:
    name: Reservation

  datasource:
#    url: jdbc:mariadb://localhost:3306/reservation?useSSL=false,useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true

  jwt:
    secret: c2VvbmdqdW4ta2FuZy16ZXJvYmFzZS1wcm9qZWN0LXNwcmluZy1yZXN0YXVyYW50LXJlc2VydmF0aW9u